# Generated by Django 4.0.2 on 2022-02-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatgroup_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(related_name='chat_groups', through='chat.ChatGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroupmember',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatgroup'),
        ),
        migrations.AddField(
            model_name='chatgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
